buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath(libs.google.oss.licenses.plugin)
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.kotlin.kapt) apply false
    alias(libs.plugins.kotlin.parcelize) apply false
    alias(libs.plugins.hilt.android) apply false
    alias(libs.plugins.google.services) apply false
    alias(libs.plugins.firebase.crashlytics) apply false
    alias(libs.plugins.roborazzi) apply false
    alias(libs.plugins.screenshotbot) apply false
    alias(libs.plugins.fulladle) apply false
    alias(libs.plugins.play.publisher) apply false
}

if (project.hasProperty("enableFladle")) {
    apply plugin: 'com.osacky.fulladle'

    fladle {
        serviceAccountCredentials = project.file("gcloud-service-key.json")
        projectId = "gratitude-journal-app"

        flankVersion = "23.10.1"

        directoriesToPull = [
                "/sdcard"
        ]

        filesToDownload = [
                "JUnitReport.xml",
                ".*/coverage/.*",
                ".*/sdcard/[^/]+\\.ec\$"
        ]

        environmentVariables = [
                coverage : "true",
                coverageFile: "/sdcard/coverage.ec"
        ]

        devices = [
                [ "model": "Pixel2.arm", "version": "27", "locale": "en_US", "orientation": "portrait" ],
        ]
    }
}

apply from: 'gradle/jacoco_ci.gradle'
apply from: 'gradle/common.gradle'
