version: 2.1

jobs:
  build_debug:
    machine:
      image: android:2025.10.1
    resource_class: large
    steps:
      - checkout
      - run:
          name: Assemble debug APKs
          command: ./gradlew assembleDebug assembleDebugAndroidTest --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apk/

  run_tests_get_coverage:
    machine:
      image: android:2025.10.1
    resource_class: large
    steps:
      - checkout
      - run:
          name: Store Google Service Account
          command: echo "$GCLOUD_SERVICE_KEY" | base64 -di > gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            gcloud auth activate-service-account presently-cicd-service-account@gratitude-journal-app.iam.gserviceaccount.com --key-file gcloud-service-key.json
            gsutil version -l
      - run:
          name: Build
          command: ./gradlew -Pcoverage assembleDebug assembleDebugAndroidTest --stacktrace
      - run:
          name: Run unit tests
          command: ./gradlew -Pcoverage testDebugUnitTest --stacktrace
      - run:
          name: Test with Firebase Test Lab
          command: ./gradlew -Pcoverage -PenableFladle runFlank --stacktrace
      - run:
          name: Copy all coverage.ec files to their respective build output package
          command: ./coverage_mover.sh
      - run:
          name: Generate JaCoCo report
          command: ./gradlew -Pcoverage jacocoFullReport --stacktrace
      - store_artifacts:
          path: build/fladle/
          destination: fladle/
      - store_artifacts:
          path: build/reports/
          destination: results/
      - store_test_results:
          path: build/

workflows:
  version: 2
  workflow:
    jobs:
      - build_debug:
          filters:
            branches:
              only: /pull\/[0-9]+/
      - run_tests_get_coverage:
          filters:
            branches:
              # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
              ignore: /pull\/[0-9]+/
