subprojects { Project project ->
    project.afterEvaluate {
        if (project.plugins.hasPlugin('com.android.library') || project.plugins.hasPlugin('com.android.application')) {
            project.android {
                buildFeatures {
                    buildConfig = true
                }
                defaultConfig {
                    //Used by custom test runner to tell FTL the module name
                    buildConfigField "String", "PROJECT_PATH", "\"" + project.path + "\""
                }
                packaging {
                    resources {
                        excludes += [
                                'META-INF/LICENSE.md',
                                'META-INF/LICENSE-notice.md'
                        ]
                    }
                }
            }
        }
    }
}
