package journal.gratitude.com.gratitudejournal.settings.model

const val FINGERPRINT = "fingerprint_lock"
const val NOTIFS_CATEGORY = "key_notifs_category"
const val NOTIFS = "notif_parent"
const val NOTIF_PREF_TIME = "pref_time"
const val EXACT_ALARMS = "exact_alarms"
const val NOTIFICATION_TROUBLESHOOTER = "notification_troubleshooter"
const val REMINDER_ONBOARDING_SEEN = "reminder_onboarding_seen"
const val NOTIFICATION_PERMISSION_REQUESTED = "notification_permission_requested"
const val THEME_PREF = "current_theme"
const val SHOW_QUOTE = "show_quote"
const val LINES_PER_ENTRY_IN_TIMELINE = "lines_per_entry_in_timeline"
const val FIRST_DAY_OF_WEEK = "first_day_of_week"
const val APP_LANGUAGE = "app_language"
const val DAY_OF_WEEK = "day_of_week"
const val NO_LANG_PREF = "no_language_selected"
const val ON_PAUSE_TIME = "last_destroy_time"
const val VERSION_PREF = "version"
const val ONE_TIME_EXPORT_PREF = "one_time_export"
const val IMPORT_PREF = "import_entries"
const val ANALYTICS_OPT_IN_PREF = "analytics_opt_out"
const val BACKUP_SETTINGS_NAVIGATION_PREF = "backup_settings_navigation"
