update_fastlane

default_platform(:android)

platform :android do

  desc "Clean up workspace"
  lane :cleanup do
    gradle(task: "clean")
  end

  desc "Run static code analysis"
  lane :static_analysis do
    gradle(task: "lint")
  end

  desc "Build variants of the app"
  lane :assemble do
    gradle(task: "assemble")
  end

  desc "Run unit tests and generate coverage report"
  lane :unit_tests do
    gradle(task: "testCoverage")
    danger(
      danger_id: "unit-tests",
      dangerfile: "Dangerfile",
      verbose: true)
  end

end
